# Generated by Django 4.2.5 on 2023-11-18 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_6', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proyecto',
            table='proyecto',
        ),
    ]
